// examples/vue/DatePicker.vue
<script setup lang="ts">
import { onMounted, ref, onScopeDispose } from 'vue'
import {
  DatePicker,
  type Days,
  type PickerLocale,
  createDate,
  formatDate,
} from "drm-datepickerjs";

const locale: PickerLocale = year => ({
  months: {
    1: { name: "January", numberOfDays: 31 },
    2: { name: "February", numberOfDays: year % 4 === 0 ? 29 : 28 },
    3: { name: "March", numberOfDays: 31 },
    4: { name: "April", numberOfDays: 30 },
    5: { name: "May", numberOfDays: 31 },
    6: { name: "June", numberOfDays: 30 },
    7: { name: "July", numberOfDays: 31 },
    8: { name: "August", numberOfDays: 31 },
    9: { name: "September", numberOfDays: 30 },
    10: { name: "October", numberOfDays: 31 },
    11: { name: "November", numberOfDays: 30 },
    12: { name: "December", numberOfDays: 31 },
  },
});

const weeksTitle = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const datepickerHeight = 300;

const date = ref(createDate())

const containerRef = ref<HTMLDivElement>();


const {
  onChangeDate,
  isOpen,
  setOpen,
  getMode,
  setMode,
  getDate,
  isSelectedDay,
  changeDay,
  getRenderedMonthName,
  getRenderedYear,
  handleShowNextMonth,
  handleShowPrevMonth,
  getMonthList,
  changeMonth,
  getYearsList,
  changeYear,
  getRenderedMonth,
  isLoading,
  goToToday,
  getDays,
  getDayMonthOffset,
} = new DatePicker({
  date: formatDate(date.value),
  locale,
  dayRenderType: "fill",
})

const handleClickOutside = event => {
  if (
      containerRef.value &&
      !containerRef.value.contains(event.target)
  ) {
      setOpen(false);
  }
};

onMounted(() => {
  onChangeDate(async () => {
    date.value = createDate(getDate())
  });

  document.addEventListener("click", handleClickOutside, true);
})

onScopeDispose(() => {
  document.removeEventListener("click", handleClickOutside, true);
})

const getPickerBackgroundColor = (
  day: Days,
  currentColor: string,
  selectColor: string,
  otherColor: string,
) => {
  if (day.state !== "current") return otherColor;
  else if (isSelectedDay(day.date)) return selectColor;
  else return currentColor;
};

const getPickerColor = (
  day: Days,
  currentColor: string,
  selectColor: string,
  otherColor: string,
) => {
  if (isSelectedDay(day.date) && day.state === "current") return selectColor;
  else if (day.state === "current") return currentColor;
  else return otherColor;
};

const dayStyle = (day: Days) => ({
  backgroundColor: getPickerBackgroundColor(
    day,
    "#cacaca",
    "#2cf2f2",
    "#d8d8d8",
  ),
  color: getPickerColor(day, "#000", "#099090", "#888"),
  width: "100%",
  border: "none",
  padding: "5px 0",
});

function getDateRef() {
  return formatDate(date.value)
}

</script>

<template>
  <div :key="getDateRef()" style="display: inline-block; width: auto;" ref="containerRef">
    <button @click="goToToday">go to today</button>


    <div  style="width: 300px">
      <input type="text" :value="getDate()" @focus="() => setOpen(true)">
    </div>

    <div v-if="isOpen() && !isLoading()" style="display: flex; width: 300px; gap: 16px; flex-direction: row;">
      <div v-if="getMode() === 'month'" style="flex: 1 ">
        <div style="display: flex; justify-content: space-between; align-items: center; flex-direction: row-reverse;">
          <div style="flex: 1; text-align: end"></div>
          <div>

            <div>
              <button style="border: none; background-color: transparent;" @click="setMode('year')">
                <span style="display: inline;">{{ getRenderedYear() }}</span>
              </button>
              <button style="border: none; background-color: transparent;" @click="setMode('month')">
                <span style="display: inline;">{{ getRenderedMonthName() }}</span>
              </button>
            </div>


          </div>
          <div style=" flex: 1">
            <button @click="setMode('day')">back</button>
          </div>
        </div>



        <div style="width: 100%; margin: 0 auto;">
          <div :style="{ overflow: 'auto', height: `${datepickerHeight}px` }">
            <div v-for="month in getMonthList()" :key="month.name"
              :style="{ backgroundColor: getRenderedMonth() === month.monthNumber ? '#cacaca' : '#fff', padding: '1px 5px' }">
              <button style="width: 100%; padding: 0; margin: 0; background-color: transparent; border: none;"
                @click="changeMonth(month.monthNumber)">
                <span>{{ month.name }}</span>
              </button>
            </div>
          </div>
        </div>
      </div>


      <div v-if="getMode() === 'year'" style="flex: 1;">
        <div style="display: flex; justify-content: space-between; align-items: center; flex-direction: row-reverse;">
          <div style="flex: 1;"></div>
          <div>

            <div>
              <button style="border: none; background-color: transparent;" @click=" setMode('year')">
                <span style="display: inline;">{{ getRenderedYear() }}</span>
              </button>
              <button style="border: none; background-color: transparent;" @click=" setMode('month')">
                <span style="display: inline;">{{ getRenderedMonthName() }}</span>
              </button>
            </div>
          </div>
          <div style="flex: 1;">
            <button @click="setMode('day')">back</button>
          </div>
        </div>

        <div style="width: 100%; margin: 0 auto;">
          <div
            :style="{ height: `${datepickerHeight}px`, display: 'flex', overflow: 'auto', flexWrap: 'wrap', gap: 3 }">
            <div v-for="year in getYearsList(1950, 2050)" :key="year"
              :style="{ backgroundColor: getRenderedYear() === year ? '#cacaca' : '#fafafa', padding: '1px 0', textAlign: 'center', width: '19%' }">
              <button @click="changeYear(year)"
                :style="{ backgroundColor: 'transparent', border: 'none', color: getRenderedYear() === year ? 'black' : '#808080' }">
                {{ year }}
              </button>
            </div>
          </div>
        </div>
      </div>

      <div v-if="getMode() === 'day' && !isLoading()" style="flex: 1;">
        <div>
          <div style="display: flex; justify-content: space-between; align-items: center;">
            <button @click="handleShowPrevMonth">prev</button>

            <div>
              <button style="border: none; background-color: transparent;" @click="setMode('year')">
                <span style="display: inline;">{{ getRenderedYear() }}</span>
              </button>
              <button style="border: none; background-color: transparent;" @click="setMode('month')">
                <span style="display: inline;">{{ getRenderedMonthName() }}</span>
              </button>
            </div>

            <button @click="handleShowNextMonth">next</button>
          </div>

          <div style="display: flex; padding: 7px 0 5px; flex-wrap: wrap;">
            <div v-for="week in weeksTitle" :key="week"
              style="background-color: #dadada; text-align: center; width: calc(100% / 7);">
              <span>{{ week }}</span>
            </div>
          </div>

          <div style="display: flex; flex-wrap: wrap;">
            <div v-for="index in Array(getDayMonthOffset(0)).fill('')" :key="index" style="width: calc(100% / 7);">
            </div>
            <div v-for="(day, index) in getDays()" :key="index" style="width: calc(100% / 7);">
              <button :style="dayStyle(day)" :disabled="day.day === 0" @click="changeDay(day.date, day.state)">
                {{ day.day }}
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
</template>

// examples/react/DatePicker.tsx
import React, {
  useState,
  useEffect,
  useRef,
  useMemo,
  useTransition,
} from "react";
import {
  DatePicker,
  Days,
  PickerLocale,
  createDate,
  formatDate,
} from "drm-datepickerjs";

const locale: PickerLocale = year => ({
  months: {
    1: { name: "January", numberOfDays: 31 },
    2: { name: "February", numberOfDays: year % 4 === 0 ? 29 : 28 },
    3: { name: "March", numberOfDays: 31 },
    4: { name: "April", numberOfDays: 30 },
    5: { name: "May", numberOfDays: 31 },
    6: { name: "June", numberOfDays: 30 },
    7: { name: "July", numberOfDays: 31 },
    8: { name: "August", numberOfDays: 31 },
    9: { name: "September", numberOfDays: 30 },
    10: { name: "October", numberOfDays: 31 },
    11: { name: "November", numberOfDays: 30 },
    12: { name: "December", numberOfDays: 31 },
  },
});

const weeksTitle = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const datepickerHeight = 300;

function SimpleDatePicker() {
  const [isPending, startTransition] = useTransition();
  const [date, setDate] = useState<Date>(createDate()); // create date based on timezone
  const containerRef = useRef<HTMLDivElement>(null);

  const monthWrapperRef = useRef<HTMLDivElement>(null);
  const yearWrapperRef = useRef<HTMLDivElement>(null);
  const selectedMonthRef = useRef<HTMLDivElement>(null);
  const selectedYearRef = useRef<HTMLDivElement>(null);

  const {
    onChangeDate,
    isOpen,
    setOpen,
    getMode,
    setMode,
    getDate,
    isSelectedDay,
    changeDay,
    getRenderedMonthName,
    getRenderedYear,
    handleShowNextMonth,
    handleShowPrevMonth,
    getMonthList,
    changeMonth,
    getYearsList,
    changeYear,
    getRenderedMonth,
    isLoading,
    goToToday,
    getDays,
    getDayMonthOffset,
  } = useMemo(
    // use memo to insure that only one instance of datePicker exist and don't change on re-rendering
    () =>
      new DatePicker({
        date: formatDate(date), // convert date to iso format YYYY-MM-DD
        locale,
        dayRenderType: "fill",
      }),
    [],
  );

  useEffect(() => {
    // change date listener
    onChangeDate(() => setDate(createDate(getDate())));

    // close date picker on click outside
    const handleClickOutside = event => {
      if (
        containerRef.current &&
        !containerRef.current.contains(event.target) &&
        !isPending
      ) {
        startTransition(() => {
          setOpen(false);
        });
      }
    };

    document.addEventListener("click", handleClickOutside, true);

    return () => {
      document.removeEventListener("click", handleClickOutside, true);
    };
  }, []);

  const daysList = getDays();

  const handleSmoothScroll = (
    parentRef: React.RefObject<HTMLDivElement>,
    itemRef: React.RefObject<HTMLDivElement>,
  ) => {
    setTimeout(() => {
      parentRef.current?.scrollTo({
        top:
          (itemRef.current?.offsetTop || 0) -
            (parentRef.current?.offsetTop || 0) -
            datepickerHeight / 2 || 0,
        left: 0,
        behavior: "smooth",
      });
    });
  };

  const RenderTitle = ({ year, month }: { year: number; month: string }) => (
    <div>
      <button
        style={{
          border: "none",
          height: "auto",
          backgroundColor: "transparent",
        }}
        onClick={() => {
          setMode("year");

          handleSmoothScroll(yearWrapperRef, selectedYearRef);
        }}
      >
        <span style={{ display: "inline" }}>{year}</span>
      </button>
      <button
        style={{
          backgroundColor: "transparent",
          border: "none",
        }}
        onClick={() => {
          setMode("month");

          handleSmoothScroll(monthWrapperRef, selectedMonthRef);
        }}
      >
        <span style={{ display: "inline" }}>{month}</span>
      </button>
    </div>
  );

  const getPickerBackgroundColor = (
    day: Days,
    currentColor: string,
    selectColor: string,
    otherColor: string,
  ) => {
    if (day.state !== "current") return otherColor;
    else if (isSelectedDay(day.date)) return selectColor;
    else return currentColor;
  };

  const getPickerColor = (
    day: Days,
    currentColor: string,
    selectColor: string,
    otherColor: string,
  ) => {
    if (isSelectedDay(day.date) && day.state === "current") return selectColor;
    else if (day.state === "current") return currentColor;
    else return otherColor;
  };

  const dayStyle = (day: Days) => ({
    backgroundColor: getPickerBackgroundColor(
      day,
      "#cacaca",
      "#2cf2f2",
      "#d8d8d8",
    ),
    color: getPickerColor(day, "#000", "#099090", "#888"),
    width: "100%",
    border: "none",
    padding: "5px 0",
  });

  return (
    <div style={{ display: "inline-block", width: "auto" }}>
      <button onClick={goToToday}>go to today</button>

      <div ref={containerRef} style={{ width: 300 }}>
        <input
          type="text"
          onFocus={() => {
            setOpen(true);
          }}
          value={getDate()}
          onChange={() => {}}
        />

        {isOpen() && !isLoading() && (
          <div
            style={{
              display: "flex",
              width: 300,
              gap: 16,
              flexDirection: "row",
            }}
          >
            {getMode() === "month" && (
              <div style={{ flex: 1 }}>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    flexDirection: "row-reverse",
                  }}
                >
                  <div style={{ flex: 1, textAlign: "end" }}></div>
                  <div>
                    <RenderTitle
                      year={getRenderedYear()}
                      month={getRenderedMonthName()}
                    />
                  </div>
                  <div style={{ flex: 1 }}>
                    <button onClick={() => setMode("day")}>back</button>
                  </div>
                </div>

                <div style={{ width: "100%", margin: "0 auto" }}>
                  <div
                    ref={monthWrapperRef}
                    style={{ height: datepickerHeight, overflow: "auto" }}
                  >
                    {getMonthList().map(month => (
                      <div
                        key={month.name}
                        ref={
                          getRenderedMonth() === month.monthNumber
                            ? selectedMonthRef
                            : undefined
                        }
                        style={{
                          backgroundColor:
                            getRenderedMonth() === month.monthNumber
                              ? "#cacaca"
                              : "#fff",
                          padding: "1px 5px",
                        }}
                      >
                        <button
                          style={{
                            width: "100%",
                            padding: 0,
                            margin: 0,
                            backgroundColor: "transparent",
                            border: "none",
                          }}
                          onClick={() => changeMonth(month.monthNumber)}
                        >
                          <span>{month.name}</span>
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {getMode() === "year" && (
              <div style={{ flex: 1 }}>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    flexDirection: "row-reverse",
                  }}
                >
                  <div style={{ flex: 1 }}></div>
                  <div>
                    <RenderTitle
                      year={getRenderedYear()}
                      month={getRenderedMonthName()}
                    />
                  </div>
                  <div style={{ flex: 1 }}>
                    <button onClick={() => setMode("day")}>back</button>
                  </div>
                </div>

                <div style={{ width: "100%", margin: "0 auto" }}>
                  <div
                    ref={yearWrapperRef}
                    style={{
                      display: "flex",
                      height: datepickerHeight,
                      overflow: "auto",
                      flexWrap: "wrap",
                      gap: 3,
                    }}
                  >
                    {getYearsList(1950, 2050).map(year => (
                      <div
                        key={year}
                        ref={
                          getRenderedYear() === year
                            ? selectedYearRef
                            : undefined
                        }
                        style={{
                          backgroundColor:
                            getRenderedYear() === year ? "#cacaca" : "#fafafa",
                          padding: "1px 0px",
                          textAlign: "center",
                          width: "19%",
                        }}
                      >
                        <button
                          onClick={() => changeYear(year)}
                          style={{
                            backgroundColor: "transparent",
                            border: "none",
                            color:
                              getRenderedYear() === year ? "black" : "#808080",
                          }}
                        >
                          {year}
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {getMode() === "day" && (
              <div style={{ flex: 1 }}>
                <div>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                    }}
                  >
                    <div>
                      <button onClick={handleShowPrevMonth}>prev</button>
                    </div>
                    <RenderTitle
                      year={getRenderedYear()}
                      month={getRenderedMonthName()}
                    />
                    <div>
                      <button onClick={handleShowNextMonth}>next</button>
                    </div>
                  </div>

                  <div
                    style={{
                      display: "flex",
                      padding: "7px 0 5px",
                      flexWrap: "wrap",
                    }}
                  >
                    {weeksTitle.map(week => (
                      <div
                        key={week}
                        style={{
                          backgroundColor: "#dadada",
                          textAlign: "center",
                          width: `${100 / 7}%`,
                        }}
                      >
                        <span>{week}</span>
                      </div>
                    ))}
                  </div>

                  <div
                    style={{
                      display: "flex",
                      flexWrap: "wrap",
                    }}
                  >
                    {/* if you using fill dayRenderType remove this block  */}
                    {Array(getDayMonthOffset(0))
                      .fill("")
                      .map((_, index) => (
                        <div
                          key={index}
                          style={{
                            width: `${100 / 7}%`,
                          }}
                        ></div>
                      ))}

                    {daysList.map((day, index) => {
                      return (
                        <div
                          key={index}
                          style={{
                            width: `${100 / 7}%`,
                          }}
                        >
                          <button
                            style={dayStyle(day)}
                            disabled={day.day === 0}
                            onClick={() => changeDay(day.date, day.state)}
                          >
                            {day.day}
                          </button>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default SimpleDatePicker;
